// Generated by custom/apply-custom.mjs. Edit custom/site.yml, then run pnpm custom:apply.
(function () {
  const texts = {
    tagText: "一览食谱助手",
    initialText: "我会根据本文整理菜品要点、食材步骤和复做提示。",
    introduceText: "你好，我是一览食谱助手。这里展示的是基于文章内容整理出的本地摘要，方便你快速判断这道菜是否适合复做。",
    generatingText: "正在整理菜谱要点..."
  };

  function typeText(el, text) {
    if (!el || !text) return;
    el.textContent = text;
  }

  function applyAiSummaryText() {
    const card = document.querySelector(".post-ai-description");
    if (!card) return;

    const tag = card.querySelector("#ai-tag");
    if (tag) tag.textContent = texts.tagText;

    const explanation = card.querySelector(".ai-explanation");
    if (explanation && /AnZhiYu|Tianli|文章辅助AI|初始化|生成中|我是/.test(explanation.textContent || "")) {
      typeText(explanation, texts.initialText);
    }

    const buttons = card.querySelectorAll(".ai-btn-item");
    if (buttons[0]) buttons[0].textContent = "介绍助手";
    if (buttons[1]) buttons[1].textContent = "整理本文要点";
    if (buttons[2]) buttons[2].textContent = "推荐相关菜谱";
    if (buttons[3]) buttons[3].textContent = "返回首页";
    const tianliButton = card.querySelector("#go-tianli-blog");
    if (tianliButton) tianliButton.style.display = "none";
  }

  function bindIntroduceText() {
    const card = document.querySelector(".post-ai-description");
    if (!card || card.dataset.yilanAiBound === "true") return;
    card.dataset.yilanAiBound = "true";

    const buttons = card.querySelectorAll(".ai-btn-item");
    if (buttons[0]) {
      buttons[0].addEventListener("click", function (event) {
        event.stopImmediatePropagation();
        event.preventDefault();
        window.setTimeout(function () {
          const explanation = card.querySelector(".ai-explanation");
          typeText(explanation, texts.introduceText);
        }, 0);
      }, true);
    }
  }

  function apply() {
    applyAiSummaryText();
    bindIntroduceText();
  }

  document.addEventListener("DOMContentLoaded", apply);
  document.addEventListener("pjax:complete", apply);
  window.setTimeout(apply, 800);
})();
